main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
	path('', views.home, name='home')
]

wtsil/urls.py
from django.urls import path, include

urlpatterns = [
	path('', include('main.urls')),
]

main/views.py
from django.shortcuts import render
from django.core.cache import cache
import time

from .apicalls import run_searches


def home(request):
	search = request.GET.get('search', '')
	if search != '':
		return results_view(request, search)
	return render(request, 'main/home.html')


def results_view(request, search):
	start = time.time()
	results = cache.get(search)
	if results is None:
		print('Making API calls')
		results = run_searches(search)
		cache.set(search, results, 60 * 60 * 12)
	else:
		print('Retrieved from cache')
	no_results = max((len(results[x]) for x in results)) == 0
	context = {'search': search, 'results': results, 'no_results': no_results}
	print(time.time() - start)
	return render(request, 'main/search.html', context)

main/templates/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="shortcut icon" type="image/png" href="{% static 'main/images/favicon.ico' %}">
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
	<link href="https://fonts.googleapis.com/css?family=Ubuntu" rel="stylesheet">
	<link rel="stylesheet" type="text/css" href="{% static 'main/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'main/style.css' %}">
	{% block head %}{% endblock %}
</head>
<body>

{% block content %}{% endblock %}

{% block scripts %}{% endblock %}
</body>
</html>

main/templates/main/home.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<title>What Technology Should I Learn?</title>
{% endblock %}


{% block content %}

<section class="home-container">
	<div class="main-search">
		<img id="home-logo" src="{% static 'main/images/wtsil-logo.png' %}">
		<h1>What Technology Should I Learn?</h1>
		{% include 'partials/search_form.html' %}
		<p>Find out what jobs in your area want from you.</p>
	</div>

	<div class="home-footer">
		<p>Job boards used:</p>
		<div class="logos">
			<a href="https://jobs.github.com/" title="GitHub Jobs">
				<img src="{% static 'main/images/GitHub-Mark-64px.png' %}">
			</a>
			<a href="https://stackoverflow.com/jobs" title="Stack Overflow Jobs">
				<img src="{% static 'main/images/so-icon.png' %}">
			</a>
			<!-- <a href="https://authenticjobs.com/" title="Authentic Jobs">
				<img src="{% static 'main/images/authentic-icon.jpg' %}">
			</a> -->
		</div>
		<i class="fa fa-arrow-circle-down scroll-arrow" id="arrow-down"></i>
	</div>
</section>

<section class="hero">
	<p class="text">
		Want to know what types of jobs are most prevalent in a certain location? Type in a city, state, or country and hit search to find out how often different programming languages, frameworks, and other keywords appear in job posts for that area.
	</p>
</section>

<div class="arrow-up-wrapper">
	<i class="fa fa-arrow-circle-up scroll-arrow" id="arrow-up"></i>
</div>

{% include 'partials/loading_modal.html' %}

{% endblock %}


{% block scripts %}
<script src="{% static 'main/autocomplete.js' %}"></script>
<script src="{% static 'main/smoothScroll.js' %}"></script>
{% endblock %}

main/templates/main/search.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<title>Results for {{ search }}</title>
{% endblock %}


{% block content %}

<main class="content-container">
	<div class="search-logo-container">
		<a href="{% url 'main:home' %}">
			<img id="results-logo" src="{% static 'main/images/wtsil-logo.png' %}">
		</a>
		{% include 'partials/search_form.html' with search=search %}
	</div>

	{% if no_results %}
	<p class="no_results">We couldn't find any job posts for this location. Your search might have been too specific, or be located in a state or country where our sites don't have much information. Please try another search.</p>

	{% else %}
	<h1 class="search-title">Results for {{ search }}</h1>

		{% for category, techs in results.items %}
			{% if techs %}
			<section class="category">
				<h2>{{ category }}</h2>

				{% if category == 'Other uncategorized keywords' %}
				<div class="other-keywords">
					{% for tech in techs %}
					<p class="other-keyword">{{ tech.name }} ({{ tech.count }})</p>
					{% endfor %}
				</div>
				
				{% else %}
				{% for tech in techs %}
				<div class="tech-container">
					<p class="tech-name">{{ tech.name }}</p>
					<div class="graph">
						<div class="bar-container" style="width:{{ tech.graph_percentage }};">
							<div class="bar"></div>
							<p class="tech-count">{{ tech.count }}</p>
						</div>
					</div>
				</div>
				{% endfor %}
				{% endif %}
			</section>
			{% endif %}
		{% endfor %}
	{% endif %}
</main>
<i class="fa fa-arrow-circle-up scroll-arrow fixed-arrow" id="arrow-up"></i>

{% include 'partials/loading_modal.html' %}

{% endblock %}


{% block scripts %}

<script>
const gray = 'rgba(128, 128, 128, 0.28)';
const palette = [
	'#ce0000',
	'#ce5d00',
	'#007c7c',
	'#00a500',
	'#2e108e',
	'#5b078a',
	'#cece00',
	'#fd44a6',
]
const bars = [];

let i = 0;
document.querySelectorAll('.category').forEach(category => {
	if (i % 2 === 0) category.style.backgroundColor = gray;
	category.querySelectorAll('.bar-container').forEach(container => {
		container.querySelector('.bar').style.backgroundColor = palette[i];
		if (!checkIfOnScreen(container)) bars.push(container);
	});
	i++;
});

window.addEventListener('scroll', () => {
	bars.forEach(container => checkIfOnScreen(container));
});

function checkIfOnScreen(container) {
	if (container.getBoundingClientRect().bottom < window.innerHeight) {
		container.style.visibility = 'visible';
		container.querySelector('.bar').classList.add('grow');
		bars.splice(bars.indexOf(container), 1);
		return true;
	}
}
</script>
<script src="{% static 'main/autocomplete.js' %}"></script>
<script src="{% static 'main/smoothScroll.js' %}"></script>

{% endblock %}

main/templates/partials/loading_modal.html
<div class="loading-modal">
	<div class="loading-icon-container">
		<h2>Searching...</h2>
		<div class="lds-ring"><div></div><div></div><div></div><div></div></div>
	</div>
</div>

main/templates/partials/search_form.html
<form class="searchbar" method="get" autocomplete="off">
	<div class="autocomplete-container">
		<div class="search-input-container">
			<input id="search-input" type="text" name="search" placeholder="City, State, Country, etc..." value="{{ search }}">
			<i id="search-clear" class="fas fa-times"></i>
		</div>
	</div>
	<button type="submit">Search</button>
</form>